### ISSUE TITLE
Vote-4-jsb

### ISSUE THREAD

**Issue by jsblair9** [Degenerate-Ape-Academy/the-daoo#8]
# You should vote for me because:
Probably shouldn't. But I'm a good developer (need someone to speak the nerd lingo) and loyal ape, I don't yell to get my way and listen thoughtfully.   

# If I'm elected, I will:
Show up

**Comment by jsblair9** [comment]
@crasskitty Can we reopen now that I fixed?

**Comment by crasskitty** [comment]
sorry you have to re-submit for the bot
